### ISSUE TITLE
rospkg.common.ResourceNotFound: tfx

### ISSUE THREAD

**Issue by mudasserzahid** [simon0793/pr2_simulation#1]
'em using ros-indigo and running this repository in catkin_workspace but its not running 
'em new to simulations project can you guide me how to run these on gazebo

**Comment by simon0793** [comment]
You need this module https://bitbucket.org/benkehoe/tfx

**Comment by mudasserzahid** [comment]
'em new to robotics so 'em unfamiliar of using libraries how i can use this , 
'em running this making a catkin_workspace
1) invoking error 
2) tfx issue (how to use)
please guide me to run these simulation step by step , i really need this
