### ISSUE TITLE
resource not found operavepy 

### ISSUE THREAD

**Issue by mudasserzahid** [simon0793/pr2_simulation#2]
hi simon 'em facing this problem after fixing tfx module issue can you please help me

**Comment by simon0793** [comment]
Hi Mudasser,

I'm not sure what you are trying to use my project for, but this simulator has some known issues and was meant as an internal evaluation of usefulness to our lab. Instead, I recommend that you read tutorials on the ROS simulator for PR2 ( http://wiki.ros.org/pr2_simulator/Tutorials ) as a starting point for your own project. 

If you are still interested in running my project code I just want you to know to that I will not be able to provide detailed assistance in getting it running on your machine. I am not currently involved in this group and I believe they have moved to a different simulator for their needs.

Again I recommend using the tutorials as a starting point, but in reference to the missing dependency in the issue, it can be found here http://openrave.org .

Good Luck on your project,
Simon

**Comment by mudasserzahid** [comment]
you have done awesome work thanks, i am new to robotics, i would love if you are taking me as junior to work with you
